services:
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg2://athena:athena@db:5432/athena
    volumes: ["./backend:/app"]
    ports: ["8000:8000"]
    depends_on: [db]

  frontend:                      #  ← ADD THIS SERVICE
    image: node:20-alpine
    working_dir: /app
    command: |
      sh -c "npm install \
             && rm -rf node_modules/.vite \
             && npm run dev -- --host 0.0.0.0"
    volumes: ["./frontend:/app"]
    ports: ["5173:5173"]

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: athena
      POSTGRES_PASSWORD: athena
      POSTGRES_DB: athena
    volumes: [pgdata:/var/lib/postgresql/data]
    ports: ["5432:5432"]

volumes:
  pgdata:
