name: alignment

on: [pull_request]

jobs:
  safety:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps
        run: pip install pytest
      - name: Run alignment tests
        run: pytest alignment_tests/ --junitxml=results.xml
      - name: Enforce threshold
        run: python scripts/check_alignment_threshold.py results.xml --fail-under 0.92
